--local grok_bo = require("grok_bo")

original_monster_on_before_hit = grok_bo.monster_on_before_hit
original_npc_on_before_hit = grok_bo.npc_on_before_hit

grok_bo.monster_on_before_hit = function(self,monster,shit,bone_id)
	wpn = level.object_by_id(shit.weapon_id)
	if wpn == nil then 
		return 
	end
	if IsGrenade(wpn) then
		return
	end
	sec = wpn:section()
	if sec == "explosive_barrel" or sec == "explosive_barrel_low" or sec == "explosive_tank" or sec == "explosive_grenade" or sec == "explosive_hide" or sec == "explosive_particle" or sec == "explosive_fuelcan" 
	or sec == "explosive_mobiltank" or sec == "explosive_dinamit" then
		return
	end
	if string.find(sec, "wpn_sks.*") and utils_item.has_this_upgrade(wpn, sec, "up_firstf_sks") then
		grok_bo.wpn_hit_power = 1.1
	end
	return original_monster_on_before_hit(self,monster,shit,bone_id)
end

grok_bo.npc_on_before_hit = function(self,monster,shit,bone_id)
	wpn = level.object_by_id(shit.weapon_id)
	if wpn == nil then 
		return 
	end
	if IsGrenade(wpn) then
		return
	end
	sec = wpn:section()
	if sec == "explosive_barrel" or sec == "explosive_barrel_low" or sec == "explosive_tank" or sec == "explosive_grenade" or sec == "explosive_hide" or sec == "explosive_particle" or sec == "explosive_fuelcan" 
	or sec == "explosive_mobiltank" or sec == "explosive_dinamit" then
		return
	end
	if string.find(sec, "wpn_sks.*") and utils_item.has_this_upgrade(wpn, sec, "up_firstf_sks") then
		grok_bo.wpn_hit_power = 1.1
	end
	return original_npc_on_before_hit(self,monster,shit,bone_id)
end
