local grok_bo = require("grok_bo")

local original_wpn_hit_power = grok_bo.wpn_hit_power

local function patchWpnHitPowerSKS()
  wpn = level.object_by_id(shit.weapon_id)

	if wpn == nil then 
		return 
	end

	if IsGrenade(wpn) then
		return
	end

	sec = wpn:section()

	if sec == "explosive_barrel" or sec == "explosive_barrel_low" or sec == "explosive_tank" or sec == "explosive_grenade" or sec == "explosive_hide" or sec == "explosive_particle" or sec == "explosive_fuelcan" 
	or sec == "explosive_mobiltank" or sec == "explosive_dinamit" then
		return
	end
  if string.find(sec, "wpn_sks.*") and utils_item.has_this_upgrade(wpn, sec, "up_firstf_sks") then
		grok_bo.wpn_hit_power = 1.1
	end
end

patchWpnHitPowerSKS()
